---
- name: IPERF3 SERVER
  hosts: SERVER
  gather_facts: false
  vars:
    ansible_user: iperf3
    ansible_ssh_pass: iperf3

  tasks:
   - name: START IPERF3 SERVER
     command: iperf3 --server --one-off --daemon

     register: iperf3_server

- name: IPERF3 CLIENT
  hosts: CLIENT
  gather_facts: false
  vars:
    ansible_user: iperf3
    ansible_ssh_pass: iperf3

  tasks:
   - name: START IPERF3 CLIENT
     command: iperf3 -c 192.168.122.171 -b 10m -t 5 -J

     register: iperf3_client

   - name: IPERF3 CLIENT OUTPUT
     debug: var=iperf3_client.stdout_lines

#- name: Insert output into JINJA2 template
#  template: >
#    src=/root/Automation/Jinja2/IPERF3.j2
#    dest=/root/Output/IPERF3/iperf3-output.txt
